### ISSUE TITLE
Captions

### ISSUE THREAD

**Issue by mrska** [ices-eg/RCGs#106]
A few possible solutions:
* [x] inclulde caption inside the plots (what about numbering)
* [x] duplicate captions (have it inside the plot and below the plot)
* [x] add new more pretty variable names
* [x] add explanation of x, y, z somewhere in the report
* [x] generate two versions of plots (one with captions inside, saved to a file,another  one without captions to the markdown and captions added inside markdown)

**Comment by Kasia-MIR** [comment]
We decided that we generate only one version of plots  (captions added inside the markdown)
