### ISSUE TITLE
Metiers: validateInputDataCodes.R shows NA values for gear_FR as invalid

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-eg/RCGs#146]
The validateInputDataCodes.R function should allow values of NA for gear_FR since that field is optional but it currently reports NAs as a validation error.  I think the code in the function should be changed as below:

  gearFR<-unique(input.data$gear_FR)
  gearFR<-gearFR[!is.na(gearFR)]
  #invalid.gearFR<-setdiff(unique(input.data$gear_FR), gear.list$gear_code)
  invalid.gearFR<-setdiff(unique(gearFR), gear.list$gear_code)

**Comment by maciek-mir** [comment]
The validateInputDataCodes.R function has been modified. NAs in gear_FR columns are no longer reported as errors.

**Comment by davidcurrie2001** [comment]
Great - thanks
