### ISSUE TITLE
aux_colours.txt

### ISSUE THREAD

**Issue by mrska** [ices-eg/RCGs#40]
After running:
` read.table('aux_colours.txt',  sep = '\t', header = TRUE)`
I got an error: _' line 2 did not have 7 elements', (but it looks like it has 7 elements)
After saving exactly the same data as .csv,  and using _read_csv()_ it works. 
Does anyone else has the same problem? Or a solution for that maybe?

**Comment by nmprista** [comment]
this worked for me
read.table("aux_colours.txt", header=T, sep="\t", colClasses="character", na.strings="", comment.char="")

**Comment by mrska** [comment]
It works. Thanks.
